/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowTintRouteImport } from './routes/window-tint'
import { Route as SpecialtyServicesRouteImport } from './routes/specialty-services'
import { Route as RetailStorefrontsRouteImport } from './routes/retail-storefronts'
import { Route as PrintedVehicleWrapsRouteImport } from './routes/printed-vehicle-wraps'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DetailingRouteImport } from './routes/detailing'
import { Route as CustomWrapWorkRouteImport } from './routes/custom-wrap-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColorChangeWrapsRouteImport } from './routes/color-change-wraps'
import { Route as AccentWrapsRouteImport } from './routes/accent-wraps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WindowTintRoute = WindowTintRouteImport.update({
  id: '/window-tint',
  path: '/window-tint',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtyServicesRoute = SpecialtyServicesRouteImport.update({
  id: '/specialty-services',
  path: '/specialty-services',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailStorefrontsRoute = RetailStorefrontsRouteImport.update({
  id: '/retail-storefronts',
  path: '/retail-storefronts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintedVehicleWrapsRoute = PrintedVehicleWrapsRouteImport.update({
  id: '/printed-vehicle-wraps',
  path: '/printed-vehicle-wraps',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailingRoute = DetailingRouteImport.update({
  id: '/detailing',
  path: '/detailing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWrapWorkRoute = CustomWrapWorkRouteImport.update({
  id: '/custom-wrap-work',
  path: '/custom-wrap-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorChangeWrapsRoute = ColorChangeWrapsRouteImport.update({
  id: '/color-change-wraps',
  path: '/color-change-wraps',
  getParentRoute: () => rootRouteImport,
} as any)
const AccentWrapsRoute = AccentWrapsRouteImport.update({
  id: '/accent-wraps',
  path: '/accent-wraps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accent-wraps': typeof AccentWrapsRoute
  '/color-change-wraps': typeof ColorChangeWrapsRoute
  '/contact': typeof ContactRoute
  '/custom-wrap-work': typeof CustomWrapWorkRoute
  '/detailing': typeof DetailingRoute
  '/gallery': typeof GalleryRoute
  '/printed-vehicle-wraps': typeof PrintedVehicleWrapsRoute
  '/retail-storefronts': typeof RetailStorefrontsRoute
  '/specialty-services': typeof SpecialtyServicesRoute
  '/window-tint': typeof WindowTintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accent-wraps': typeof AccentWrapsRoute
  '/color-change-wraps': typeof ColorChangeWrapsRoute
  '/contact': typeof ContactRoute
  '/custom-wrap-work': typeof CustomWrapWorkRoute
  '/detailing': typeof DetailingRoute
  '/gallery': typeof GalleryRoute
  '/printed-vehicle-wraps': typeof PrintedVehicleWrapsRoute
  '/retail-storefronts': typeof RetailStorefrontsRoute
  '/specialty-services': typeof SpecialtyServicesRoute
  '/window-tint': typeof WindowTintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accent-wraps': typeof AccentWrapsRoute
  '/color-change-wraps': typeof ColorChangeWrapsRoute
  '/contact': typeof ContactRoute
  '/custom-wrap-work': typeof CustomWrapWorkRoute
  '/detailing': typeof DetailingRoute
  '/gallery': typeof GalleryRoute
  '/printed-vehicle-wraps': typeof PrintedVehicleWrapsRoute
  '/retail-storefronts': typeof RetailStorefrontsRoute
  '/specialty-services': typeof SpecialtyServicesRoute
  '/window-tint': typeof WindowTintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accent-wraps'
    | '/color-change-wraps'
    | '/contact'
    | '/custom-wrap-work'
    | '/detailing'
    | '/gallery'
    | '/printed-vehicle-wraps'
    | '/retail-storefronts'
    | '/specialty-services'
    | '/window-tint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accent-wraps'
    | '/color-change-wraps'
    | '/contact'
    | '/custom-wrap-work'
    | '/detailing'
    | '/gallery'
    | '/printed-vehicle-wraps'
    | '/retail-storefronts'
    | '/specialty-services'
    | '/window-tint'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accent-wraps'
    | '/color-change-wraps'
    | '/contact'
    | '/custom-wrap-work'
    | '/detailing'
    | '/gallery'
    | '/printed-vehicle-wraps'
    | '/retail-storefronts'
    | '/specialty-services'
    | '/window-tint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccentWrapsRoute: typeof AccentWrapsRoute
  ColorChangeWrapsRoute: typeof ColorChangeWrapsRoute
  ContactRoute: typeof ContactRoute
  CustomWrapWorkRoute: typeof CustomWrapWorkRoute
  DetailingRoute: typeof DetailingRoute
  GalleryRoute: typeof GalleryRoute
  PrintedVehicleWrapsRoute: typeof PrintedVehicleWrapsRoute
  RetailStorefrontsRoute: typeof RetailStorefrontsRoute
  SpecialtyServicesRoute: typeof SpecialtyServicesRoute
  WindowTintRoute: typeof WindowTintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window-tint': {
      id: '/window-tint'
      path: '/window-tint'
      fullPath: '/window-tint'
      preLoaderRoute: typeof WindowTintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialty-services': {
      id: '/specialty-services'
      path: '/specialty-services'
      fullPath: '/specialty-services'
      preLoaderRoute: typeof SpecialtyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail-storefronts': {
      id: '/retail-storefronts'
      path: '/retail-storefronts'
      fullPath: '/retail-storefronts'
      preLoaderRoute: typeof RetailStorefrontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printed-vehicle-wraps': {
      id: '/printed-vehicle-wraps'
      path: '/printed-vehicle-wraps'
      fullPath: '/printed-vehicle-wraps'
      preLoaderRoute: typeof PrintedVehicleWrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailing': {
      id: '/detailing'
      path: '/detailing'
      fullPath: '/detailing'
      preLoaderRoute: typeof DetailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-wrap-work': {
      id: '/custom-wrap-work'
      path: '/custom-wrap-work'
      fullPath: '/custom-wrap-work'
      preLoaderRoute: typeof CustomWrapWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-change-wraps': {
      id: '/color-change-wraps'
      path: '/color-change-wraps'
      fullPath: '/color-change-wraps'
      preLoaderRoute: typeof ColorChangeWrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accent-wraps': {
      id: '/accent-wraps'
      path: '/accent-wraps'
      fullPath: '/accent-wraps'
      preLoaderRoute: typeof AccentWrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccentWrapsRoute: AccentWrapsRoute,
  ColorChangeWrapsRoute: ColorChangeWrapsRoute,
  ContactRoute: ContactRoute,
  CustomWrapWorkRoute: CustomWrapWorkRoute,
  DetailingRoute: DetailingRoute,
  GalleryRoute: GalleryRoute,
  PrintedVehicleWrapsRoute: PrintedVehicleWrapsRoute,
  RetailStorefrontsRoute: RetailStorefrontsRoute,
  SpecialtyServicesRoute: SpecialtyServicesRoute,
  WindowTintRoute: WindowTintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
